### ISSUE TITLE
近期出现访问不通的情况

### ISSUE THREAD

**Issue by xiajunyi** [ark930/shanghai-bus#1]
作者你好：

       首先，感谢您在github上的发布，我有幸看到了这个shanghai-bus的程序，于是自己简单发布用来做小程序的后台来测试，感觉这是个非常不错的程序。
       昨天，不知是上海发布的接口进行了调整还是加强了校验，该程序不能够正常的访问了。
       如果你有时间，希望您能帮忙看一下是否可以有解决方法，非常感谢！

**Comment by chlv** [comment]
上海发布接口发生变化：
http --> https
公交线路查询网址变换 https://shanghaicity.openservice.kankanews.com/public/bus/mes/sid/{sid}?stoptype=1
首末班车 网页解析元素变化 //div[@class='upgoing cur ' or @class='upgoing ']/p/span/text()

参考代码：
https://github.com/chlv/shanghaibus/blob/master/main.py

**Comment by chlv** [comment]
> 作者你好：
> 
> ```
>    首先，感谢您在github上的发布，我有幸看到了这个shanghai-bus的程序，于是自己简单发布用来做小程序的后台来测试，感觉这是个非常不错的程序。
>    昨天，不知是上海发布的接口进行了调整还是加强了校验，该程序不能够正常的访问了。
>    如果你有时间，希望您能帮忙看一下是否可以有解决方法，非常感谢！
> ```
上海发布接口发生变化：
http --> https
公交线路查询网址变换 https://shanghaicity.openservice.kankanews.com/public/bus/mes/sid/{sid}?stoptype=1
首末班车 网页解析元素变化 //div[@Class='upgoing cur ' or @Class='upgoing ']/p/span/text()

参考代码：
https://github.com/chlv/shanghaibus/blob/master/main.py

**Comment by xiajunyi** [comment]
已经解决，非常感谢！！！
